# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obeya < Formula
  desc "CLI Kanban board for humans and AI agents"
  homepage "https://github.com/schoolofai/obeya"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.2/obeya_0.1.2_darwin_amd64.tar.gz"
      sha256 "f6333f72c4908b1cd1f841cfffaf8535537a84451ae35b7ab92dbcf4e7eeb34e"

      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.2/obeya_0.1.2_darwin_arm64.tar.gz"
      sha256 "09f71d1ade711a909737f85b232c4af1c5f3a0022cf9ee8377bb44e13d18396f"

      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.2/obeya_0.1.2_linux_amd64.tar.gz"
      sha256 "941a650d12c86e48d079b8177f69ebec567a2742fc24c23b4c5d3aaa68dd2d15"
      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.2/obeya_0.1.2_linux_arm64.tar.gz"
      sha256 "d7df17063aa7939c0415e9a5a7711dd5434c933d63263ecf64a883add61615d7"
      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  test do
    system "#{bin}/ob", "--help"
  end
end
