# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obeya < Formula
  desc "CLI Kanban board for humans and AI agents"
  homepage "https://github.com/schoolofai/obeya"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schoolofai/obeya/releases/download/v0.2.0/obeya_0.2.0_darwin_amd64.tar.gz"
      sha256 "22f1d631defa46682cc00835474b341968dfa6b09dbd9c87ddcb3eeb41a12bef"

      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schoolofai/obeya/releases/download/v0.2.0/obeya_0.2.0_darwin_arm64.tar.gz"
      sha256 "6ce9d9945b685985f66ed52786dc4cdb0855f9ef87738a2cf21c53df82765f9c"

      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.2.0/obeya_0.2.0_linux_amd64.tar.gz"
      sha256 "93d782b3db0c00cc6d3bd8fe18d10ad54693e5053eb2771a32b12d2d009f2e2e"
      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.2.0/obeya_0.2.0_linux_arm64.tar.gz"
      sha256 "a45185cd98c4961d72ac0c60782527da99c407cf2c5a6208842a4bbadb1976aa"
      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  test do
    system "#{bin}/ob", "--help"
  end
end
