# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Obeya < Formula
  desc "CLI Kanban board for humans and AI agents"
  homepage "https://github.com/schoolofai/obeya"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.3/obeya_0.1.3_darwin_amd64.tar.gz"
      sha256 "805f3b135ec8e37fee001f8f168295887727b397c5c75614869c9cf91835ec31"

      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.3/obeya_0.1.3_darwin_arm64.tar.gz"
      sha256 "f2022eb7ebdae3b6b888fb67d23acb870b8a0a593f60bd6c408914cdcfa81f52"

      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.3/obeya_0.1.3_linux_amd64.tar.gz"
      sha256 "c554595d8e6261af2cb4ae5fa178cf613d0bf14df3bd85790caf5a97a6e93597"
      define_method(:install) do
        bin.install "ob"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/schoolofai/obeya/releases/download/v0.1.3/obeya_0.1.3_linux_arm64.tar.gz"
      sha256 "355d235f8487d63155a9b79098a153cd30563bc225b08e3f8ed5a860e1f0f923"
      define_method(:install) do
        bin.install "ob"
      end
    end
  end

  test do
    system "#{bin}/ob", "--help"
  end
end
